Categories:
- Name: General
  Services:
  - Source: Azure_logo_icon_50
    Target: Azure

- Name: AIMachineLearning
  Services:
  - Source: Azure Batch AI
    Target: AzureBatchAI   
  - Source: Azure Bot Service
    Target: AzureBotService
  - Source: Azure Cognitive Services
    Target: AzureCognitiveServices
  - Source: Azure Machine Learning Service
    Target: AzureMachineLearningService
  - Source: Azure Machine Learning Studio
    Target: AzureMachineLearningStudio
  - Source: Microsoft Genomics
    Target: MicrosoftGenomics

- Name: Analytics
  Services:
  - Source: AzureStreamAnalytics
    Target: AzureStreamAnalytics
  - Source: Azure Databricks
    Target: AzureDatabricks
  - Source: AzureHDInsight
    Target: AzureHDInsight
  - Source: Azure Data Lake Analytics
    Target: AzureDataLakeAnalytics
  - Source: Azure Analysis Service
    Target: AzureAnalysisServices
  - Source: Azure Event Hubs
    Target: AzureEventHub    
  - Source: Azure Data Catalog
    Target: AzureDataCatalog
  - Source: Azure Data Explorer
    Target: AzureDataExplorer    

- Name: Compute
  Services:
  - Source: Azure Virtual Machine
    Target: AzureVirtualMachine
  - Source: Azure App Service
    Target: AzureAppService
  - Source: Azure Functions
    Target: AzureFunction
  - Source: Azure Batch
    Target: AzureBatch
  - Source: Azure Service Fabric
    Target: AzureServiceFabric
  - Source: Azure VM Scale Set
    Target: AzureVirtualMachineScaleSet

- Name: Containers
  Services:
  - Source: Azure Container Registry
    Target: AzureContainerRegistry
  - Source: container-instances
    Target: AzureContainerInstance
  - Source: Azure Service Fabric Mesh
    Target: AzureServiceFabricMesh
  - Source: Azure Kubernetes Service
    Target: AzureKubernetesService   
  - Source: app-service-containers
    Target: AzureWebAppForContainers

- Name: Databases
  Services:
  - Source: Azure SQL Database
    Target: AzureSqlDatabase
  - Source: CosmosDB
    Target: AzureCosmosDb
  - Source: Azure SQL DataWarehouse
    Target: AzureSqlDataWarehouse
  - Source: Data Factory
    Target: AzureDataFactory
  - Source: Azure Cache plus Redis
    Target: AzureRedisCache
  - Source: SQL Server stretch Databases
    Target: AzureSqlStretchDatabase
  - Source: postgresql
    Target: AzureDatabaseForPostgreSQL
  - Source: mysql
    Target: AzureDatabaseForMySQL
  - Source: Azure Database MariaDB
    Target: AzureDatabaseForMariaDB

- Name: DevOps
  Services:
  - Source: Azure DevOps
    Target: AzureDevOps
  - Source: Azure Boards
    Target: AzureBoards
  - Source: Azure Pipelines
    Target: AzurePipelines
  - Source: Azure Repos
    Target: AzureRepos
  - Source: Azure Test Plans
    Target: AzureTestPlans
  - Source: Azure Artifacts
    Target: AzureArtifacts
  - Source: Application Insights
    Target: AzureApplicationInsights
  - Source: Azure DevTest Labs
    Target: AzureDevTestLabs
  - Source: Azure Lab Services
    Target: AzureLabServices

- Name: Identity
  Services:
  - Source: Azure Active Directory
    Target: AzureActiveDirectory
  - Source: ActiveDirectoryDomain
    Target: AzureActiveDirectoryDomainServices
  - Source: ActiveDirectoryB2C
    Target: AzureActiveDirectoryB2C

- Name: Integration
  Services:
  - Source: Azure Event Grid
    Target: AzureEventGrid
  - Source: Logic Apps
    Target: AzureLogicApps
  - Source: Azure Service Bus
    Target: AzureServiceBus
  - Source: Event Grid Topics
    Target: EventGridTopics
  - Source: Event Grid Subscriptions
    Target: EventGridSubscriptions
  - Source: Event Grid Domains
    Target: EventGridDomains
  - Source: Azure Service Bus Relays
    Target: AzureServiceBusRelays
  - Source: Logic Apps Custom Connector
    Target: LogicAppsCustomConnector
  - Source: API Management Services
    Target: APIManagementServices

- Name: InternetOfThings
  Services:
  - Source: Azure IoT Hub
    Target: AzureIoTHub
  - Source: IOT edge
    Target: AzureIoTEdge
  - Source: IoT_Central_50
    Target: AzureIoTCentral
  - Source: Azure Time Series Insights
    Target: AzureTimeSeriesInsights
  - Source: azure-maps
    Target: AzureMaps
  - Source: Azure Digital Twins
    Target: AzureDigitalTwins

- Name: Management
  Services:
  - Source: Backup
    Target: AzureBackup
  - Source: Azure Site Recovery
    Target: AzureSiteRecovery
  - Source: Azure Scheduler
    Target: AzureScheduler
  - Source: Automation
    Target: AzureAutomation
  - Source: Azure Log Analytics
    Target: AzureLogAnalytics
  - Source: Azure Monitor
    Target: AzureMonitor
  - Source: Azure Resource Groups
    Target: AzureResourceGroups
  - Source: AzurePolicy
    Target: AzurePolicy
  - Source: Azure Blueprints
    Target: AzureBlueprints
  - Source: Azure Subscription New
    Target: AzureSubscription
  - Source: Azure Management Groups
    Target: AzureManagementGroups
  - Source: Azure Managed Applications
    Target: AzureManagedApplications   
           
- Name: Media
  Services:
  - Source: Azure Media Services
    Target: AzureMediaServices

- Name: Mobile
  Services:
  - Source: AzureNotificationHubs
    Target: AzureNotificationHubs
  - Source: Azure App Service - Mobile App
    Target: AzureMobileApp
    
- Name: Networking
  Services:
  - Source: Azure ExpressRoute
    Target: AzureExpressRoute 
  - Source: Azure DNS
    Target: AzureDNS   
  - Source: Azure Virtual Network
    Target: AzureVirtualNetwork
  - Source: Traffic Manager Profiles
    Target: AzureTrafficManager
  - Source: Load Balancers
    Target: AzureLoadBalancer
  - Source: Azure VPN Gateway
    Target: AzureVPNGateway
  - Source: AzureApplicationGateway
    Target: AzureApplicationGateway
  - Source: ddos-protection
    Target: AzureAzureDDoSProtection
  - Source: virtual-wan
    Target: AzureVirtualWAN
  - Source: Azure Front Door Service
    Target: AzureFrontDoorService

- Name: Security
  Services:
  - Source: Azure Key Vault
    Target: AzureKeyVault
  - Source: Azure Sentinel
    Target: AzureSentinel    

- Name: Storage
  Services:
  - Source: Azure Storage
    Target: AzureStorage
  - Source: Azure StorSimple
    Target: AzureStorSimple
  - Source: Data Lake Store
    Target: AzureDataLakeStorage
  - Source:  Storage - Blob
    Target: AzureBlobStorage
  - Source: disks
    Target: AzureDiskStorage
  - Source: managed-disks
    Target: AzureManagedDisks
  - Source: Azure Storage - Queue
    Target: AzureQueueStorage
  - Source: Azure Storage - Files
    Target: AzureFileStorage
  - Source: Azure Data Box
    Target: AzureDataBox
  - Source: Azure NetApp Files
    Target: AzureNetAppFiles

- Name: Web
  Services:
  - Source: CDN Profiles
    Target: AzureCDN
  - Source: API Management Services

    Target: AzureAPIManagement
  - Source: Azure Search
    Target: AzureSearch
  - Source: Azure App Service - Web App (was Websites)
    Target: AzureWebApp
  - Source: Azure SignalR Service
    Target: AzureSignalRService
    
- Name: Office365
  Services:
  - Source: Dynamics
    Target: DynamicsService
  - Source: powerbi
    Target: powerbi
  - Source: exchange
    Target: exchange

- Name: ThirdParty
  Services:
  - Source: Mandrill
    Target: Mandrill