Categories:
- Name: Integration
  Services:
  - Source: Azure Event Grid
    Target: AzureEventGrid
  - Source: Azure Logic Apps
    Target: AzureLogicApps
  - Source: Azure Service Bus
    Target: AzureServiceBus
  - Source: API Management Services
    Target: APIManagementServices
  - Source: Event Grid Topics
    Target: EventGridTopics
  - Source: Event Grid Subscriptions
    Target: EventGridSubscriptions
  - Source: Event Grid Domains
    Target: EventGridDomains
  - Source: Azure Service Bus Relays
    Target: AzureServiceBusRelays
  - Source: Logic Apps Custom Connector
    Target: LogicAppsCustomConnector

- Name: Dynamics
  Services:
  - Source: dynamics
    Target: Dynamics365

- Name: ThirdParty
  Services:
  - Source: Mandrill
    Target: Mandrill